### ISSUE TITLE
file extension in classification_results.csv file

### ISSUE THREAD

**Issue by abhishm** [ignaciorlando/refuge-evaluation#1]
What is the file extension should we choose for classification.csv file. I chose the ".jpg"  extension. But this extension will not work with the evaluation code because it requires the ".bmp" extension.

**Comment by ignaciorlando** [comment]
Hi @abhishm!

The code for evaluating the classification results does not need to "see" files with the extension .bmp. We require the filenames in the classification_results.csv file to be equal to the names of the files in the validation set, which are all .jpg extension. 

We only require the files to be exported as bmp for the segmentations tasks, as jpg uses lossy compression and it might introduce noise in the labeling.

Let me know if you still have problems and I'll reopen the issue!
